<#import "blocks/template.ftlh" as t>
<@t.template user>
    <h1 style="text-align: center">Контактные данные</h1>
    <hr>
    <h4>МТС:      +375 29 288-33-87</h4>
    <h4>Viber:    +375 29 288-33-87</h4>
    <h4>Telegram: @electromark</h4>
    <h4>Почта: admin@electromark.by</h4>
    <br>
    <h1 style="text-align: center">Магазина</h1>
    <hr>
    <h4>Адрес: пр-т Я.Купалы, 87 (ТРК «Тринити», 3 этаж)</h4>
    <h4>График работы: с 10:00 до 22:00 (пн - вс)</h4>
    <br>
</@t.template>